### ISSUE TITLE
Persist URL list

### ISSUE THREAD

**Issue by njacques** [njacques/TabTastic#5]
We need to store the list of URLs, their date added, and category

**Comment by njacques** [comment]
I'm thinking maybe [PouchDB](https://pouchdb.com/) for this?

**Comment by jameshibbard** [comment]
What does that give us over IndexedDB?

**Comment by njacques** [comment]
It's a lightweight wrapper for IndexedDB - simplifies the use (https://gist.github.com/BigstickCarpet/a0d6389a5d0e3a24814b#gistcomment-1854985),

**Edit**: although [Dexie](http://dexie.org/) looks very interesting too
