### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by njacques** [njacques/TabTastic#6]
We need to think about how the UI is going to work, past dumping all the open tabs into the inbox.

**Follow up tasks:**

* Format tab suspender
* Drag and drop (?)

**Comment by njacques** [comment]
I was thinking along the lines of a simplified version of the Todoist UI:

![todoist ui](https://user-images.githubusercontent.com/385573/39593009-fad3579a-4ede-11e8-858f-c1af2f3fa79d.png)

**Comment by jameshibbard** [comment]
Looks very appealing. Maybe have a look at using a Material Design theme or something?
